### ISSUE TITLE
Duplicates return after pressing Tab (or alt-Tab) key

### ISSUE THREAD

**Issue by veksha** [RevenantX/foo_cuefixer#1]
Default user interface

I have:
  two facets panes (one for Artists, one for Albums);
  one playlist view;

first bug:
when i select artist for the _first time_ then select album for the _first time_ duplicates appear.
when i change selection of albums back and forth duplicates are filtered out correctly.

second bug:
if duplicates are filtered out correctly then when I press alt-tab (once or twice, depends if you have another window opened) duplicates reappear.
OR I can press just Tab key several times to change focus to different panes and REFERENCED_FILEs appear in playlist along with .CUE or .APL.

![screenshot](https://i.imgur.com/N60tmbt.jpg)

**Comment by RevenantX** [comment]
@veksha @svefn @Klaster1 fixed

**Comment by RevenantX** [comment]
https://github.com/RevenantX/foo_cuefixer/releases/tag/1.24
