### ISSUE TITLE
Crash when using Cue fixer 1.3

### ISSUE THREAD

**Issue by Whosondephone** [RevenantX/foo_cuefixer#10]
Ive been experiencing a crash when cuefixer is loaded.  It happens when I try to make a playlist with my entire lossless collection.  The collection consists of over 165,000 items.  It doesn't happen when I remove cuefixer.  I've tried beta versions of Foobar and will tinker a bit more with the 32bit version of Foobar.  

I think it might be in the realm of possibility that I have duplicate Cue files in some albums.  One referencing a wave file and one referencing a flac file.

[failure_00000009.txt](https://github.com/RevenantX/foo_cuefixer/files/12615723/failure_00000009.txt)

**Comment by RevenantX** [comment]
@Whosondephone should be fixed in 1.31

**Comment by RevenantX** [comment]
https://github.com/RevenantX/foo_cuefixer/commit/583e468cba3180c007379e972e59f3ceb2d999a3

**Comment by Whosondephone** [comment]
Thank you!  This has been quite a treat!
