### ISSUE TITLE
Music folders added to the media library can't exclude entire tracks

### ISSUE THREAD

**Issue by simear2004** [RevenantX/foo_cuefixer#14]
The music folder added to the media library does not exclude the entire track, and manually dragging into the playlist works fine

**Comment by simear2004** [comment]
Found what's causing this problem, please ignore this feedback!

**Comment by skytree2181301** [comment]
> Found what's causing this problem, please ignore this feedback!

I'm using foo_cuefixer 1.3.2 and I'm experiencing the same issue. Could you please tell me how you resolved it?

**Comment by skytree2181301** [comment]
@simear2004 I'm using foo_cuefixer 1.3.2 and I'm experiencing the same issue. Could you please tell me how you resolved it?
