### ISSUE TITLE
Case sensitive path compare on Windows

### ISSUE THREAD

**Issue by CrendKing** [RevenantX/foo_cuefixer#15]
It seems foo_cuefixer uses [metadb::path_compare](https://github.com/RevenantX/foo_cuefixer/blob/204b5dee8e3f90d3b49271b6ef7310376ff5be75/src/foo_cuefixer.cpp#L65) to compare the reference file with the file on disk. According to the foobar2000 SDK, this comparison is case sensitive by default unless caller changes the `case_sensitive` value. However, as you may know, Windows file system is case insensitive. This leads to situation where the referenced file (e.g. `CDImage.flac` vs `CDimage.flac`) is found and added but the filter seemingly doesn't remove it from the playlist.

**Comment by RevenantX** [comment]
fixed https://github.com/RevenantX/foo_cuefixer/commit/c936542705a9910fdb73b46ca2fead6cd4c32b1f
