### ISSUE TITLE
Saving a playlist with links to tracks in cue files

### ISSUE THREAD

**Issue by Krulk** [RevenantX/foo_cuefixer#17]
Is it possible to make foobar2000 save a playlist in .m3u8 with a link to specific tracks in the cue file? And not with a link to a cue file without tracks.

**Comment by RevenantX** [comment]
@Krulk seems according to Wikipedia M3U cannot contain links to tracks inside CUE/FLAC: https://en.wikipedia.org/wiki/M3U

**Comment by Krulk** [comment]
Thank you, even foo_xspf_1 by default does not save individual tracks in xspf, it has an xml format with a bunch of unnecessary information, but it cannot save an individual track, it opens the entire album, or I was unable to configure it, pity.
