### ISSUE TITLE
foo_cuefixer 1.24 is broken when used on windows 7.

### ISSUE THREAD

**Issue by Rollinnn** [RevenantX/foo_cuefixer#2]
32-bit windows 7, foobar2000 1.6.7, foo_cuefixer 1.24. Not possible to open any cue at all.
There is no problem on 64-bit windows 10.

**Comment by RevenantX** [comment]
@Rollinnn try latest version

**Comment by Rollinnn** [comment]
Yes, it is fixed in 1.3.
