### ISSUE TITLE
64-bit version for new foobar v2

### ISSUE THREAD

**Issue by CarloApri** [RevenantX/foo_cuefixer#4]
Is it possible to add the 64-bit version of the component?

**Comment by CarloApri** [comment]
@RevenantX

**Comment by RevenantX** [comment]
@carlox97 yes, i will update it

**Comment by CarloApri** [comment]
> @carlox97 yes, i will update it

Thank you! You did a wonderful job with this tool, a life saver!

**Comment by danielliulihua** [comment]
I have downloaded FB2K SDK and tried to build a 64-bit lib with visual stdio 2022 64-bit, without luck after "retarget solution". maybe I used the latest SDK which have different folder structure with the one you used(a lot of .h file not found, I tried to included them one by one, other .h keeping missing/not found). is it possible to share your SDK?

**Comment by RevenantX** [comment]
@danielliulihua i used foobar sdk, it just need be recompiled (all libs too). I will make new versions with little fixes (little memory leak)

**Comment by RevenantX** [comment]
@carlox97 @danielliulihua fixed by https://github.com/RevenantX/foo_cuefixer/commit/64fca563a06c57b86155c6f0617c457db3c4a462
