### ISSUE TITLE
? sign in the cue's FILE lines crashes foobar

### ISSUE THREAD

**Issue by dezdem** [RevenantX/foo_cuefixer#6]
the FILE's value containing the question mark crashes foobar.
I have some broken .cue files which point to the blablalba?.flac e.g.
whenever I use ColumnsUI's filter to choose the artist/album with such .cues foobar (2.0) crashes.

**Comment by RevenantX** [comment]
should be fixed with 1.31

**Comment by RevenantX** [comment]
https://github.com/RevenantX/foo_cuefixer/commit/583e468cba3180c007379e972e59f3ceb2d999a3
