### ISSUE TITLE
Not working with the 64bit version of foobar2000 2.1 preview 2023-08-24

### ISSUE THREAD

**Issue by Whosondephone** [RevenantX/foo_cuefixer#9]
I'm not sure if I'm misunderstanding the functionality of this plugin but it does not appear to be working on 64bit version of Foobar2000.  The screenshot show an older preview version but I updated to the latest and still have issue.  Again I'm not sure exactly how this works, but I'm expecting at the very least that the original flac file gets hidden if there is a cue sheet in the same folder.  Also I would hope there should be pseudo files listed in the library.
![foobar](https://github.com/RevenantX/foo_cuefixer/assets/67973433/eb8d6fae-06c1-496f-bc3c-bca05d6c8d76)

**Comment by RevenantX** [comment]
@Whosondephone what about stable foobar release?

>but I'm expecting at the very least that the original flac file gets hidden if there is a cue sheet in the same folder. Also I would hope there should be pseudo files listed in the library.

Yes it should work that way. Maybe some problem of beta.

**Comment by Whosondephone** [comment]
Completely uninstalled Foobar2000 and all settings.  Installed V2.0 64bit.  Added foo_cuefixer and still not working.  Could it be my core 2 quad?

**Comment by RevenantX** [comment]
@Whosondephone what if you open/move that album to playlist from library? It works with playlists, not with library directly

**Comment by Whosondephone** [comment]
You are correct!  Works perfectly!   : D
